### ISSUE TITLE
Memory leak with `USBInput`

### ISSUE THREAD

**Issue by Huizerd** [aestream/aestream#107] opened 2024-05-31 07:40 UTC
Running this MWE (based on the `usb_stream.py` example) gives me a memory leak, no matter the settings (backend, device, dt) I use:

```python
import time

from aestream import USBInput

# settings
device = "cuda"  # cpu or cuda
backend = "torch"  # torch or numpy
dt_desired = 0.001  # 1ms

with USBInput((240, 180), device=device) as stream:
    while True:
        t0 = time.time()

        # process stuff here
        frame = stream.read(backend)

        dt_actual = time.time() - t0
        if dt_actual < dt_desired:
            time.sleep(dt_desired - dt_actual)
        else:
            print("actual dt > desired dt")

        print(f"actual dt {dt_actual:.5f} s, compensated dt {time.time() - t0:.5f} s")
```

I ran it with a kind of broken DVS240 that outputs a lot of events, so maybe that makes it more visible. Have you noticed this kind of behaviour before? I saw #90, but that was about AEDAT. If I use the CLI, e.g. `aestream input inivation output view` I don't see a memory leak. I compiled everything as described in #106.

**Comment by Jegp** [comment] 2024-05-31 17:35
We noticed it once for the GPU tensors, where the pointer wasn't properly garbage collected once we handed it over to nanobind. But I never had that for the USBInput, despite using cameras for a long time. So, this is really strange. 

My thinking is that it can both be on the AEStream side or the driver side. Knowing Inivation, it's probably AEStream. Do you have experience debugging this @Huizerd? I can try on my side, but I only have a DVXplorer camera available at the moment.

**Comment by Huizerd** [comment] 2024-06-04 06:11
I don't have experience in debugging this, but I'll try. I just tested with a well-functioning DVS240, there the problem is the same. Could you confirm that you don't have a memory leak when you run the code above with the DVXplorer with a fresh install of aestream (and maybe libcaer/CUDA)?

**Comment by Jegp** [comment] 2024-06-05 05:29
I investigated with a DVXplorer camera via CLI. First by dumping `/proc/x/smaps` in the beginning of the process and after running it for ~10 minutes. I couldn't find anything significant, although the memory buffer is varying wildly, from 2kB to 65mB.

Next, I used [Valgrind](https://stackoverflow.com/questions/5134891/how-do-i-use-valgrind-to-find-memory-leaks) to detect memory leaks. They did find quite a few potential leaks when opening the device, but none in the running code, and we're talking ~10kB over ~10 minutes. Report is below:

```==52789== LEAK SUMMARY:
 ==52789==    definitely lost: 128 bytes in 2 blocks
 ==52789==    indirectly lost: 24 bytes in 1 blocks
 ==52789==      possibly lost: 7,056 bytes in 56 blocks
 ==52789==    still reachable: 1,079 bytes in 8 blocks
 ==52789==         suppressed: 0 bytes in 0 blocks
```

Next, I tried with the Python version using the `examples/usb_stream.py` script. Dumping the smaps also didn't show any leak. The memory would just increase/decrease over time, but I didn't see any trend after 10 minutes. I tried Valgrind here, but it froze when writing the report. Maybe because of the Python callstack?

So far, I haven't found any smoking gun in the CLI or Python stacks. But note that this is purely CPU. I haven't tried CUDA yet.

Any luck on your end?

**Comment by Huizerd** [comment] 2024-06-06 10:39
I just tested a bit more, and even when running `example/usb_stream.py` (changing the resolution to fit the 240x180 of the DVS240) and installing without CUDA (by setting `CMAKE_ARGS="-DUSE_CUDA=0"` before the `pip ...` command) still gives me a very slow but steady memory increase. I'll try to use some of the tools you named to quantify it. Building with or without CUDA didn't seem to matter, but shorter `interval` made the leak more apparent. It didn't matter whether the camera moved or not, the leak was just as big when there were 0 events constantly.

**Comment by Jegp** [comment] 2024-06-07 03:53
Yeah, something is definitely wrong. It would likely be in the handling of the Python tensor frames. They're quite big (`240x180` per interval), so if they're not cleaned up they will cause a huge mess. One way to test that would be to run aestream from the command line, which should be installed via pip as well. Could you try something like `aestream input inivation` and see whether the memory of that process grows?

Regarding the Python part, could you try updating `nanobind` manually?

Finally, it's odd that I can't seem to reproduce it on my end. Are you on Linux? And which compiler and version are you using?

**Comment by Huizerd** [comment] 2024-06-07 15:21
I will check the handling of tensors and look at `nanobind`.

When I do `aestream input inivation` or `aestream input inivation output view` the memory doesn't seem to grow.

I am on Ubuntu 20.04, with GCC and G++ 10 (see the config in #106).

**Comment by Huizerd** [comment] 2024-06-15 13:24
Yes! That solves it for me. Great!

**Comment by Jegp** [comment] 2024-06-15 21:34
Happy to hear! I'll close the issue, merge the branch and release a new version to propagate the fix. Feel free to reopen if you run into problems.

**Closed by Jegp** 2024-06-15 21:34 UTC
